plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.6'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.vaadin' version '25.1.5' //'24.4.4' //MS added
}

group = 'com.usmb.but3'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
	// MS added for Mockito agent
    // out : 19/06 mockitoAgent
}

repositories {
	mavenCentral()
}

ext {
	//vaadinVersion = '24.4.4' // MS added
	vaadinVersion = '25.1.5' // MS added
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-flyway'
	implementation 'org.flywaydb:flyway-database-postgresql'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	// MS added for Mockito agent
    // out : 19/06 testImplementation 'org.mockito:mockito-core:5.2.0' // or your version
    // out : 19/06 mockitoAgent 'org.mockito:mockito-core:5.2.0' // or your version
	// MS added for Hibernate schema generation
	implementation 'org.hibernate:hibernate-core:6.3.0.Final'
	// MS added for Vaadin
	implementation 'com.vaadin:vaadin-spring-boot-starter'
	implementation 'org.springframework.security:spring-security-crypto'
	developmentOnly('com.vaadin:vaadin-dev')
	testRuntimeOnly 'com.h2database:h2'
	testImplementation 'org.springframework.boot:spring-boot-data-jpa-test'
	implementation 'org.apache.poi:poi-ooxml:5.2.5'
	implementation 'com.opencsv:opencsv:5.9'
}

dependencyManagement {  // MS added for Vaadin BOM
	imports {
		mavenBom "com.vaadin:vaadin-bom:${vaadinVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
	/* MS added for Mockito agent
    doFirst {
        jvmArgs += "-javaagent:${configurations.mockitoAgent.asPath}"
    } out !  :19/06 */
}
