spring.application.name=td4biblio
spring.jackson.property-naming-strategy: SNAKE_CASE
spring.flyway.locations: classpath:/db/migration
spring.flyway.schemas: biblio
spring.flyway.baselineOnMigrate: true
spring.flyway.enabled: true
#spring.flyway.loggers=
spring.datasource.driverClassName: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://localhost:5432/biblio?currentSchema=biblio
spring.datasource.username: postgres
spring.datasource.password: postgres
# Logging configuration
logging.file.name=logs/td4biblio.log
logging.level.root=INFO
logging.level.com.usmb.but3.td2biblio=DEBUG
# Tracer dans la console les requêtes SQL effectuées par Hibernate :
spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.logs:true

# Hibernate configuration
#spring.jpa.hibernate.ddl-auto: update
#spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect   
#spring.jpa.properties.hibernate.format_sql: true
#spring.jpa.properties.hibernate.use_sql_comments: true
spring.jdbc.template.max-rows=500
# NO schema.sql file created by Hibernare with : 
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.hbm2ddl.auto=create
#spring.jpa.properties.hibernate.hbm2ddl.schema_generation.script_ddl_output=./schema.sql
#spring.jpa.properties.hibernate.hbm2ddl.schema_generation.create-source=metadata
#spring.jpa.properties.hibernate.hbm2ddl.schema_generation.scripts.action=create

#added to avoid the error : hot reloading failed
spring.jmx.enabled=false